<a href="https://colab.research.google.com/github/risekus/linear_algebra2/blob/main/%EC%8B%A4%EC%8A%B5Zero_ipynb%EC%9D%98_%EC%82%AC%EB%B3%B8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("Hello World")

#integer
x = 3
print ("정수: %01d, %02d, %03d, %04d, %05d"
      % ( x,x,x,x,x))

# float
x = 256.123
print ( "실수: %.0f, %.1f, %.2f"
      %(x,x,x))

# string
x = "hello, world"
print ("문자열: [%s]" % (x))

Hello World
정수: 3, 03, 003, 0003, 00003
실수: 256, 256.1, 256.12
문자열: [hello, world]


반복문,조건문

In [ ]:
contents = ["regression", "classification", "svm", "clustering", "dimension reduction",
            "nn", "cnn", "ae", "gan", "rnn"]
for con in contents:
  if con in ["regression", "classification", "svm", "clustering", "dimension reduction"]:
    print ("%s 은(는) 기계학습 내용입니다." %con)
  elif con in ["cnn"]:
    print("%s 은(는) convolutional neural network입니다." %con)
  else:
    print ("%s은(는) 심층학습 내용입니다." %con)

regression 은(는) 기계학습 내용입니다.
classification 은(는) 기계학습 내용입니다.
svm 은(는) 기계학습 내용입니다.
clustering 은(는) 기계학습 내용입니다.
dimension reduction 은(는) 기계학습 내용입니다.
nn은(는) 심층학습 내용입니다.
cnn 은(는) convolutional neural network입니다.
ae은(는) 심층학습 내용입니다.
gan은(는) 심층학습 내용입니다.
rnn은(는) 심층학습 내용입니다.


반복문과 인덱스

In [ ]:
for (i,con) in enumerate(contents):
  print ("[%d/%d]: %s" %(i, len(contents), con))

[0/10]: regression
[1/10]: classification
[2/10]: svm
[3/10]: clustering
[4/10]: dimension reduction
[5/10]: nn
[6/10]: cnn
[7/10]: ae
[8/10]: gan
[9/10]: rnn


함수

In [ ]:
def sum(a,b):
  return a+b

x = 10.0
y = 20.0
print ("%.1f + %.1f = %.1f" %(x, y, sum(x,y)))

10.0 + 20.0 = 30.0


리스트

In [ ]:
a = []
b = [1,2,3]
c = ["hello", ",", "world"]
d = [1,2,3,"x", "y", "z"]
x = []
print (x)

x.append('a')
print(x)

x.append(123)
print(x)

x.append(["a", "b"])
print (x)


[]
['a']
['a', 123]
['a', 123, ['a', 'b']]


딕셔너리

In [ ]:
dic = dict()
dic["name"] = "daesik"
dic["town"] = "yongin city"
dic["job"] = "assistant professor"
print (dic)

{'name': 'daesik', 'town': 'yongin city', 'job': 'assistant professor'}


클래스

In [ ]:
class student:
  # 생성자
  def __init__(self, name):
    self.name = name
  def study(self, hard=False):
    if hard:
      print ("%s 학생은 열심히 공부합니다." %self.name)
    else:
      print ("%s 학생은 공부합니다." %self.name)

s = student('daesik')
s.study()
s.study(hard = True)

daesik 학생은 공부합니다.
daesik 학생은 열심히 공부합니다.


2. 벡터, 행렬 연산, 그래프 그리기

라이브러리 로드

In [ ]:
import numpy as np


프린트

In [ ]:
def print_val(x):
  print ("Type:", type(x))
  print ("shape:", x.shape)
  print ("값:\n", x)
  print (" ")

rank 1 up array

In [ ]:
x = np.array([1, 2, 3])
print_val(x)

x[0] = 5
print_val(x)

랜덤행렬

In [ ]:
a = np.random.random((4, 4))
print_val(a)

Type: <class 'numpy.ndarray'>
shape: (4, 4)
값:
 [[0.95924919 0.21456381 0.09855097 0.76096286]
 [0.40406424 0.56007999 0.54911765 0.70007953]
 [0.42158557 0.3020866  0.75588932 0.05320152]
 [0.6306974  0.77322692 0.41545671 0.86072935]]
 


In [ ]:
a = np.random.randn(4,4)
print_val(a)

Type: <class 'numpy.ndarray'>
shape: (4, 4)
값:
 [[ 0.15587131 -0.04876607  0.18263039  0.87937573]
 [ 1.96158195  0.04404019 -1.75693701 -0.11879391]
 [ 0.26518703  1.22027213  0.16090392 -1.01851839]
 [ 0.35907768  0.72002272  0.1209801  -0.44638948]]
 


np array indexing

In [ ]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print_val(a)

Type: <class 'numpy.ndarray'>
shape: (3, 4)
값:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
 


In [ ]:
b = a[:2, 1:3]
print_val(b)

Type: <class 'numpy.ndarray'>
shape: (2, 2)
값:
 [[2 3]
 [6 7]]
 
